services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - backend-npm-cache:/root/.npm
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - keycloak
    environment:
      - NODE_ENV=development
      - TS_NODE_PROJECT=./tsconfig.json
    restart: unless-stopped
    stdin_open: true
    tty: true

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - frontend-npm-cache:/root/.npm
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=true
    depends_on:
      - backend
    restart: unless-stopped
    stdin_open: true
    tty: true

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment: {}
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    restart: unless-stopped

volumes:
  mongo-data:
  backend-npm-cache:
  frontend-npm-cache:
  keycloak-data: 